### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by rikorikardo** [rlinxy/Uniminer#1]
Hi trying launch on ubuntu 18 with nvidia drivers 440 and always got error (core dumped illegal instruction), maybe i should need install some speific liblaries? help pls

**Comment by rlinxy** [comment]
Try to use the command line as below:
./UniMiner-linux -a x17r -o stratum+tcp://127.0.0.1:10102 -u walletaddress.%computername% -i 21
replace the 'walletaddress' with your own address.
